# Generated by Django 4.1 on 2024-06-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
        ),
    ]
